# -*- coding: utf-8 -*-
"""ISTA_322_Fa24_HW3_sarayu_gadi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAW5C_xJIOJ4Yflw526qu5SLWlfQC2gw

#HW3 - SQL

This homework has you working with a new database of information on ticket sales for various types of events.  Your job will be to do some initial exploring and then demonstrate your ability to do all the different types of SQL queries we learned over the last two week.  You'll also need to make one function that'll make looking at the tables easier.

These questions are written in the way someone would ask them to you.  In other words, I'm using 'plain english' questions vs. ones where I'm very explicit in terms of what columns and tables to use.  Your exploring of the database and functions to ease that process will come in handy here!  

The database has been created using a set of data from Amazon. You can read more about what each table contains here: https://docs.aws.amazon.com/redshift/latest/dg/c_sampledb.html.

## Libraries and import functions

First bring the libraries we'll need!
"""

import psycopg2
import pandas as pd

"""Now bring in all our functions we used in the lessons!  """

# Make our connection/cursor function
AWS_host_name = "ticketsdb.chwicm24ose3.us-east-1.rds.amazonaws.com"
AWS_dbname = "ticketsdb"
AWS_user_name = "postgres"
AWS_password = "ista322ticketsdb"

def get_conn_cur(): # define function name and arguments (there aren't any)
  # Make a connection
  conn = psycopg2.connect(
    host=AWS_host_name,
    database=AWS_dbname,
    user=AWS_user_name,
    password=AWS_password,
    port='5432')

  cur = conn.cursor()   # Make a cursor after

  return(conn, cur)   # Return both the connection and the cursor

# Same run_query function
def run_query(query_string):

  conn, cur = get_conn_cur() # get connection and cursor

  cur.execute(query_string) # executing string as before

  my_data = cur.fetchall() # fetch query data as before

  # here we're extracting the 0th element for each item in cur.description
  colnames = [desc[0] for desc in cur.description]

  cur.close() # close
  conn.close() # close

  return(colnames, my_data) # return column names AND data

# Column name function for checking out what's in a table
def get_column_names(table_name): # arguement of table_name
  conn, cur = get_conn_cur() # get connection and cursor

  # Now select column names while inserting the table name into the WERE
  column_name_query =  """SELECT column_name FROM information_schema.columns
       WHERE table_name = '%s' """ %table_name

  cur.execute(column_name_query) # exectue
  my_data = cur.fetchall() # store

  cur.close() # close
  conn.close() # close

  return(my_data) # return

# Check table_names
def get_table_names():
  conn, cur = get_conn_cur() # get connection and cursor

  # query to get table names
  table_name_query = """SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public' """

  cur.execute(table_name_query) # execute
  my_data = cur.fetchall() # fetch results

  cur.close() #close cursor
  conn.close() # close connection

  return(my_data) # return your fetched results

"""## Q1 Make a SQL head function - 5 point

Make function to get the pandas equivalent of `.head()`

This function should be called `sql_head` and take a single argument of `table_name` where you specify the table name you want the head information from.  It should return the column names along with the first five rows of the table along.  

**For full points, return a pandas dataframe with this information so it displays nicely :)**
"""

## Q1 Your function starts here
# make sql_head function
def sql_head(table_name):
    conn, cur = get_conn_cur()
    query = f"SELECT * FROM {table_name} LIMIT 5"
    sql_head_df = pd.read_sql_query(query, conn)
    cur.close()
    conn.close()

    return sql_head_df

get_table_names()

# Check that it works!
sql_head(table_name = 'sales')
## Q1 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q2 Explore and SELECT - 5 point

Let's start this homework with some basic queries to get a look at what's in the various tables.  I want you to do the following.

* Use your get_table_names() function to see what tables are in the database.
* Use your get_column_names() to get the column names of each of the tables.  **Do this all within a single cell to keep it neat**.
* Make and run a query that selects all columns from the event table.  Only return the first 5 rows.
* Use the `sql_head()` function you created to get the first five rows of the sales table.
"""

## Q2 Your function starts here
# Getting table names
get_table_names()

# Getting column names
for i in get_table_names():
  print(get_column_names(table_name = i[0]))

# Could also just use a list comprehension vs a bunch of print statements :)
names = get_table_names()
[get_column_names(table_name= x) for x in names]

# Query on events
sq = """ SELECT *
FROM event
LIMIT 5"""
run_query(sq)

# Use sql_head to get the head of sales
sql_head(table_name = 'sales')
## Q2 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q3 WHERE - 5 points

Now let's do a bit of filtering with WHERE.  Write and run queries to get the following results.  
**LIMIT all returns to first five rows.**

* Get venues (**full row of data, including venue_id, etc.**) with >= 10000 seats from the venues table
* Get venues (**full row of data, including venue_id, etc.**) in Arizona
* Get users (**just the first names**) who have a first name that starts with H
* Get the email addresses (**just the email addresses**) of users who gave a .edu email address



"""

## Q3 Your function starts here
# Get big venues... so those with >= than 10000 seats
sq1 = """ SELECT *
          FROM venue
          WHERE venue_seats >= 10000
          LIMIT 5"""

run_query(sq1)

# Get venues in AZ
sq2 = """ SELECT *
          FROM venue
          WHERE venue_state = 'AZ'
          LIMIT 5;"""
run_query(sq2)

#Get users who have a first name that starts with H
sq3 = """ SELECT first_name
          FROM users
          WHERE first_name LIKE 'H%'
          LIMIT 5;"""
run_query(sq3)

# Get all .edu email addresses... just the email addresses
sq4 = """ SELECT email
          FROM users
          WHERE email LIKE '%.edu'
          LIMIT 5;"""
run_query(sq4)
## Q3 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q4 GROUP BY and HAVING - 5 points

Time to practice some GROUP BY and HAVING operations. Please write and run queries that do the following:

GROUP BY application
* Find the top five venues that hosted the most events: Alias the count of events as 'events_hosted'. Also return the venue ID
* Get the number of events hosted in each month. You'll need to use `date_part()` in your select to select just the months. Alias this as 'month' and then the count of the number of events hosted as 'events_hosted'.
* Get the top five sellers who made the most commission. Alias their total commission made as 'total_com'. Also get their average commission made and alias as 'avg_com'.  Be sure to also display the seller_id.  

HAVING application
* Using the same query as the last one, instead of getting the top five sellers get all sellers who have made a total commission greater than $4000.
* Using the same query as the first groupby, instead of returning the top five venues, return just the ID's of venues that have had greater than 60 events.
"""

## Q4 Your function starts here
### GROUP BY application
# Find the top five venues that hosted the most events: Alias the count of events as 'events_hosted'. Also return the venue ID
sq1 = """ SELECT venue_id,
          COUNT(*) AS events_hosted
          FROM venue
          GROUP BY venue_id
          ORDER BY events_hosted DESC
          LIMIT 5;"""
run_query(sq1)

# Get the number of events hosted in each month. You'll need to use `date_part()` in your select to select just the months.
# Alias this as 'month' and then the count of the number of events hosted as 'events_hosted'
sq2 = """ SELECT date_part('month', start_time) AS month,
          COUNT(*) AS events_hosted
          FROM event
          GROUP BY month
          ORDER BY month;"""
run_query(sq2)

sql_head(table_name = 'event')

# Get the top five sellers who made the most commission. Alias their total commission made as 'total_com'.
# Also get their average commission made and alias as 'avg_com'. Be sure to also display the seller_id
sq3 = """ SELECT seller_id,
       SUM(commission) AS total_com,
       AVG(commission) AS avg_com
       FROM sales
       GROUP BY seller_id
       ORDER BY total_com DESC
       LIMIT 5;"""
run_query(sq3)

### HAVING application
# Using the same query as the last groupby, instead of getting the top five sellers get all sellers who have made a total commission greater than $4000
sq4 = """ SELECT seller_id,
          SUM(commission) AS total_com,
          AVG(commission) AS avg_com
          FROM sales
          GROUP BY seller_id
          HAVING SUM(commission) > 4000
          ORDER BY total_com DESC;"""
run_query(sq4)

# Using the same query as the first groupby, instead of returning the top five venues, return just the ID's of venues that have had greater than 60 events
sq5 = """ SELECT venue_id
          FROM event
          GROUP BY venue_id
          HAVING COUNT(*) > 60
          LIMIT 5;"""
run_query(sq5)
## Q4 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q5 JOIN - 5 points

Time for some joins. You've probably noticed by now that there is at least one relational key in each table, but some have more.  For example, sales has a unique sale id, listing id, seller id, buyer id, date id.  This allows you to link each sale to relevant information in other tables.  
**LIMIT each output to 5**

Please write queries to do the following items:

* Join information of users to each sale made.  
* Join information about each venue to each event.
"""

## Q5 Your function starts here
sq1 = """ SELECT * FROM sales
          LIMIT 5;"""
run_query(sq1)

sq2 = """ SELECT * FROM users
          LIMIT 5;"""
run_query(sq2)

get_column_names(table_name='users')

get_column_names(table_name='sales')

# Join users information to each sale
sq3 = """ SELECT *
          FROM sales
          JOIN users
          ON sales.buyer_id = users.user_id
          LIMIT 5;"""
run_query(sq3)

# For each event attach the venue information
sq4 = """ SELECT *
          FROM event
          JOIN venue
          ON event.venue_id = venue.venue_id
          LIMIT 5;"""
run_query(sq4)
## Q5 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q 6 Subqueries - 5 points

To wrap up let's do several subqueries. Please do the following:

* Get all purchases made by users of live in Arizona
* Get event information for all events that took place in a venue where the venue name ends with 'Stadium'.
* Get event information for all events where the total ticket sales were greater than $50,000.  
"""

## Q6 Your function starts here
# Get all purchases from users who live in Arizona
sq1 = """ SELECT *
          FROM sales
          WHERE buyer_id IN (SELECT user_id
          FROM users
          WHERE state = 'AZ');"""
run_query(sq1)

# Get event information for all events that took place in a venue where the name ended in 'Stadium'
sq2 = """ SELECT e.*
          FROM event e
          JOIN venue v ON e.venue_id = v.venue_id
          WHERE v.venue_name LIKE '%Stadium';"""
run_query(sq2)

# Get event information where the total sales for that event were greater than $50000
sq3 = """ SELECT e.*
          FROM event e
          WHERE e.event_id IN (
          SELECT s.event_id
          FROM sales s
          GROUP BY s.event_id
          HAVING SUM(s.price_paid) > 50000);"""
run_query(sq3)

get_table_names()

get_column_names(table_name= 'date')

## Q6 Your function ends here - Any code outside of these start/end markers won't be graded